### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by parkt90** [JerckyLY/cesium-demo-view#1]
作者你好，看到你的博哥，写的很棒。但是当我尝试运行这个项目demo时，发现都会报错。
报错如下：
SecurityError: Failed to construct 'Worker': Script at 'file:///E:/cesium/cesium-demo-view/Cesium/Workers/cesiumWorkerBootstrapper.js' cannot be accessed from origin 'null'.

Error: Failed to construct 'Worker': Script at 'file:///E:/cesium/cesium-demo-view/Cesium/Workers/cesiumWorkerBootstrapper.js' cannot be accessed from origin 'null'.
    at createWorker (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:259813)
    at TaskProcessor.scheduleTask (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:261475)
    at HeightmapTerrainData.createMesh (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:270033)
    at transform$1 (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:2593120)
    at processTerrainStateMachine (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:2591380)
    at Function.GlobeSurfaceTile.processStateMachine (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:2596300)
    at GlobeSurfaceTileProvider.loadTile (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:2641068)
    at processSinglePriorityLoadQueue (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:2696235)
    at processTileLoadQueue (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:2695780)
    at QuadtreePrimitive.endFrame (file:///E:/cesium/cesium-demo-view/Cesium/Cesium.js:1:2686217)
请问是我缺少什么东西吗？还是没有正确运行？希望你能抽出时间看看，我将不胜感激。

**Comment by parkt90** [comment]
以及解决了。
